import React from "react";
import { Link } from "react-router-dom";
const Home = () => {
  return (
    <div className="dhiwise-navigation">
      <h1>Homepage</h1>
      <p className="headline">
        This project was generated By{" "}
        <a href="https://www.dhiwise.com">Dhiwise</a>. Quickly use below links
        to navigate through all pages.
      </p>
      <ul>
        <li>
          <Link to="/homepagedesktop">HomePageDesktop</Link>
        </li>
        <li>
          <Link to="/aboutuspagedesktop">AboutUsPageDesktop</Link>
        </li>
        <li>
          <Link to="/propertiespagedesktop">PropertiesPageDesktop</Link>
        </li>
        <li>
          <Link to="/propertydetailspagedesktop">
            PropertyDetailsPageDesktop
          </Link>
        </li>
        <li>
          <Link to="/servicespagedesktop">ServicesPageDesktop</Link>
        </li>
        <li>
          <Link to="/contactpagedesktop">ContactPageDesktop</Link>
        </li>
      </ul>
    </div>
  );
};
export default Home;
